--[[----------------------------------------------------------------------------

  LiteMount/MountDB/Expansion.lua

  This used to be done by some kind of minID-maxID system but Blizzard's mount
  development and release process hasn't worked that way since Dragonflight.
  As long as I update this before each xpac ends it's easier to keep the
  complete list and then anything else is the current xpac.

----------------------------------------------------------------------------]]--

local _, LM = ...

LM.MountDB = LM.MountDB or {}

local Expansion = {
    [0] = { -- Classic
        [   6] = true, -- Brown Horse
        [   7] = true, -- Gray Wolf
        [   8] = true, -- White Stallion
        [   9] = true, -- Black Stallion
        [  11] = true, -- Pinto
        [  12] = true, -- Black Wolf
        [  13] = true, -- Red Wolf
        [  14] = true, -- Timber Wolf
        [  15] = true, -- Winter Wolf
        [  17] = true, -- Felsteed
        [  18] = true, -- Chestnut Mare
        [  19] = true, -- Dire Wolf
        [  20] = true, -- Brown Wolf
        [  21] = true, -- Gray Ram
        [  22] = true, -- Black Ram
        [  24] = true, -- White Ram
        [  25] = true, -- Brown Ram
        [  26] = true, -- Striped Frostsaber
        [  27] = true, -- Emerald Raptor
        [  28] = true, -- Skeletal Horse
        [  31] = true, -- Spotted Frostsaber
        [  32] = true, -- Tiger
        [  34] = true, -- Striped Nightsaber
        [  35] = true, -- Ivory Raptor
        [  36] = true, -- Turquoise Raptor
        [  38] = true, -- Violet Raptor
        [  39] = true, -- Red Mechanostrider
        [  40] = true, -- Blue Mechanostrider
        [  41] = true, -- Warhorse
        [  42] = true, -- White Mechanostrider Mod B
        [  43] = true, -- Green Mechanostrider
        [  45] = true, -- Black Nightsaber
        [  46] = true, -- Ancient Frostsaber
        [  50] = true, -- Red Wolf
        [  51] = true, -- Arctic Wolf
        [  52] = true, -- Palomino
        [  53] = true, -- White Stallion
        [  54] = true, -- Mottled Red Raptor
        [  55] = true, -- Winterspring Frostsaber
        [  56] = true, -- Ivory Raptor
        [  57] = true, -- Green Mechanostrider
        [  58] = true, -- Unpainted Mechanostrider
        [  62] = true, -- Icy Blue Mechanostrider Mod A
        [  63] = true, -- Frost Ram
        [  64] = true, -- Black Ram
        [  65] = true, -- Red Skeletal Horse
        [  66] = true, -- Blue Skeletal Horse
        [  67] = true, -- Brown Skeletal Horse
        [  68] = true, -- Green Skeletal Warhorse
        [  69] = true, -- Rivendare's Deathcharger
        [  70] = true, -- Riding Kodo
        [  71] = true, -- Gray Kodo
        [  72] = true, -- Brown Kodo
        [  73] = true, -- Green Kodo
        [  74] = true, -- Teal Kodo
        [  75] = true, -- Black War Steed
        [  76] = true, -- Black War Kodo
        [  77] = true, -- Black Battlestrider
        [  78] = true, -- Black War Ram
        [  79] = true, -- Black War Raptor
        [  80] = true, -- Red Skeletal Warhorse
        [  81] = true, -- Black War Tiger
        [  82] = true, -- Black War Wolf
        [  83] = true, -- Dreadsteed
        [  84] = true, -- Charger
        [  85] = true, -- Swift Mistsaber
        [  87] = true, -- Swift Frostsaber
        [  88] = true, -- Swift Yellow Mechanostrider
        [  89] = true, -- Swift White Mechanostrider
        [  90] = true, -- Swift Green Mechanostrider
        [  91] = true, -- Swift Palomino
        [  92] = true, -- Swift White Steed
        [  93] = true, -- Swift Brown Steed
        [  94] = true, -- Swift Brown Ram
        [  95] = true, -- Swift Gray Ram
        [  96] = true, -- Swift White Ram
        [  97] = true, -- Swift Blue Raptor
        [  98] = true, -- Swift Olive Raptor
        [  99] = true, -- Swift Orange Raptor
        [ 100] = true, -- Purple Skeletal Warhorse
        [ 101] = true, -- Great White Kodo
        [ 102] = true, -- Great Gray Kodo
        [ 103] = true, -- Great Brown Kodo
        [ 104] = true, -- Swift Brown Wolf
        [ 105] = true, -- Swift Timber Wolf
        [ 106] = true, -- Swift Gray Wolf
        [ 107] = true, -- Swift Stormsaber
        [ 108] = true, -- Frostwolf Howler
        [ 109] = true, -- Stormpike Battle Charger
        [ 110] = true, -- Swift Razzashi Raptor
        [ 111] = true, -- Swift Zulian Tiger
        [ 116] = true, -- Black Qiraji Battle Tank
        [ 117] = true, -- Blue Qiraji Battle Tank
        [ 118] = true, -- Red Qiraji Battle Tank
        [ 119] = true, -- Yellow Qiraji Battle Tank
        [ 120] = true, -- Green Qiraji Battle Tank
        [ 121] = true, -- Black Qiraji Battle Tank
        [ 122] = true, -- Black Qiraji Battle Tank
    },

    [1] = { -- Burning Crusade
        [ 123] = true, -- Nether Drake
        [ 125] = true, -- Riding Turtle
        [ 129] = true, -- Golden Gryphon
        [ 130] = true, -- Ebon Gryphon
        [ 131] = true, -- Snowy Gryphon
        [ 132] = true, -- Swift Blue Gryphon
        [ 133] = true, -- Tawny Wind Rider
        [ 134] = true, -- Blue Wind Rider
        [ 135] = true, -- Green Wind Rider
        [ 136] = true, -- Swift Red Wind Rider
        [ 137] = true, -- Swift Red Gryphon
        [ 138] = true, -- Swift Green Gryphon
        [ 139] = true, -- Swift Purple Gryphon
        [ 140] = true, -- Swift Green Wind Rider
        [ 141] = true, -- Swift Yellow Wind Rider
        [ 142] = true, -- Swift Purple Wind Rider
        [ 145] = true, -- Blue Mechanostrider
        [ 146] = true, -- Swift Pink Hawkstrider
        [ 147] = true, -- Brown Elekk
        [ 149] = true, -- Thalassian Charger
        [ 150] = true, -- Thalassian Warhorse
        [ 151] = true, -- Dark War Talbuk
        [ 152] = true, -- Red Hawkstrider
        [ 153] = true, -- Cobalt War Talbuk
        [ 154] = true, -- White War Talbuk
        [ 155] = true, -- Silver War Talbuk
        [ 156] = true, -- Tan War Talbuk
        [ 157] = true, -- Purple Hawkstrider
        [ 158] = true, -- Blue Hawkstrider
        [ 159] = true, -- Black Hawkstrider
        [ 160] = true, -- Swift Green Hawkstrider
        [ 161] = true, -- Swift Purple Hawkstrider
        [ 162] = true, -- Swift Warstrider
        [ 163] = true, -- Gray Elekk
        [ 164] = true, -- Purple Elekk
        [ 165] = true, -- Great Green Elekk
        [ 166] = true, -- Great Blue Elekk
        [ 167] = true, -- Great Purple Elekk
        [ 168] = true, -- Fiery Warhorse
        [ 169] = true, -- Swift Nether Drake
        [ 170] = true, -- Cobalt Riding Talbuk
        [ 171] = true, -- Dark Riding Talbuk
        [ 172] = true, -- Silver Riding Talbuk
        [ 173] = true, -- Tan Riding Talbuk
        [ 174] = true, -- White Riding Talbuk
        [ 176] = true, -- Green Riding Nether Ray
        [ 177] = true, -- Red Riding Nether Ray
        [ 178] = true, -- Purple Riding Nether Ray
        [ 179] = true, -- Silver Riding Nether Ray
        [ 180] = true, -- Blue Riding Nether Ray
        [ 183] = true, -- Ashes of Al'ar
        [ 185] = true, -- Raven Lord
        [ 186] = true, -- Onyx Netherwing Drake
        [ 187] = true, -- Azure Netherwing Drake
        [ 188] = true, -- Cobalt Netherwing Drake
        [ 189] = true, -- Purple Netherwing Drake
        [ 190] = true, -- Veridian Netherwing Drake
        [ 191] = true, -- Violet Netherwing Drake
        [ 196] = true, -- Spectral Tiger
        [ 197] = true, -- Swift Spectral Tiger
        [ 199] = true, -- Amani War Bear
        [ 201] = true, -- Brewfest Ram
        [ 202] = true, -- Swift Brewfest Ram
        [ 203] = true, -- Cenarion War Hippogryph
        [ 204] = true, -- Turbo-Charged Flying Machine
        [ 205] = true, -- Flying Machine
        [ 206] = true, -- Merciless Nether Drake
        [ 207] = true, -- Merciless Nether Drake
        [ 213] = true, -- Swift White Hawkstrider
        [ 219] = true, -- Headless Horseman's Mount
        [ 220] = true, -- Black War Elekk
        [ 222] = true, -- Swift Zhevra
        [ 223] = true, -- Vengeful Nether Drake
        [ 224] = true, -- Swift Zhevra
        [ 225] = true, -- Brewfest Riding Kodo
        [ 226] = true, -- Great Brewfest Kodo
        [ 241] = true, -- Brutal Nether Drake
        [ 243] = true, -- Big Blizzard Bear
    },

    [2] = { -- Wrath of the Litch King
        [ 211] = true, -- X-51 Nether-Rocket
        [ 212] = true, -- X-51 Nether-Rocket X-TREME
        [ 221] = true, -- Acherus Deathcharger
        [ 230] = true, -- Big Battle Bear
        [ 236] = true, -- Winged Steed of the Ebon Blade
        [ 237] = true, -- White Polar Bear
        [ 240] = true, -- Mechano-Hog
        [ 246] = true, -- Azure Drake
        [ 247] = true, -- Blue Drake
        [ 248] = true, -- Bronze Drake
        [ 249] = true, -- Red Drake
        [ 250] = true, -- Twilight Drake
        [ 251] = true, -- Black Polar Bear
        [ 253] = true, -- Black Drake
        [ 254] = true, -- Black War Mammoth
        [ 255] = true, -- Black War Mammoth
        [ 256] = true, -- Wooly Mammoth
        [ 257] = true, -- Wooly Mammoth
        [ 258] = true, -- Ice Mammoth
        [ 259] = true, -- Ice Mammoth
        [ 262] = true, -- Red Proto-Drake
        [ 263] = true, -- Black Proto-Drake
        [ 264] = true, -- Blue Proto-Drake
        [ 265] = true, -- Time-Lost Proto-Drake
        [ 266] = true, -- Plagued Proto-Drake
        [ 267] = true, -- Violet Proto-Drake
        [ 268] = true, -- Albino Drake
        [ 269] = true, -- Armored Brown Bear
        [ 270] = true, -- Armored Brown Bear
        [ 271] = true, -- Black War Bear
        [ 272] = true, -- Black War Bear
        [ 273] = true, -- Grand Caravan Mammoth
        [ 274] = true, -- Grand Caravan Mammoth
        [ 275] = true, -- Mekgineer's Chopper
        [ 276] = true, -- Armored Snowy Gryphon
        [ 277] = true, -- Armored Blue Wind Rider
        [ 278] = true, -- Green Proto-Drake
        [ 279] = true, -- Magnificent Flying Carpet
        [ 280] = true, -- Traveler's Tundra Mammoth
        [ 284] = true, -- Traveler's Tundra Mammoth
        [ 285] = true, -- Flying Carpet
        [ 286] = true, -- Grand Black War Mammoth
        [ 287] = true, -- Grand Black War Mammoth
        [ 288] = true, -- Grand Ice Mammoth
        [ 289] = true, -- Grand Ice Mammoth
        [ 291] = true, -- Blue Dragonhawk
        [ 292] = true, -- Red Dragonhawk
        [ 293] = true, -- Illidari Doomhawk
        [ 294] = true, -- Stormwind Steed
        [ 295] = true, -- Darkspear Raptor
        [ 296] = true, -- Ironforge Ram
        [ 297] = true, -- Darnassian Nightsaber
        [ 298] = true, -- Gnomeregan Mechanostrider
        [ 299] = true, -- Exodar Elekk
        [ 300] = true, -- Orgrimmar Wolf
        [ 301] = true, -- Thunder Bluff Kodo
        [ 302] = true, -- Silvermoon Hawkstrider
        [ 303] = true, -- Forsaken Warhorse
        [ 304] = true, -- Mimiron's Head
        [ 305] = true, -- Argent Hippogryph
        [ 306] = true, -- Ironbound Proto-Drake
        [ 307] = true, -- Rusted Proto-Drake
        [ 308] = true, -- Blue Skeletal Warhorse
        [ 309] = true, -- White Kodo
        [ 310] = true, -- Black Wolf
        [ 311] = true, -- Venomhide Ravasaur
        [ 312] = true, -- Sea Turtle
        [ 313] = true, -- Deadly Gladiator's Frost Wyrm
        [ 314] = true, -- Black Skeletal Horse
        [ 317] = true, -- Furious Gladiator's Frost Wyrm
        [ 318] = true, -- Great Red Elekk
        [ 319] = true, -- Swift Moonsaber
        [ 320] = true, -- Swift Red Hawkstrider
        [ 321] = true, -- Swift Gray Steed
        [ 322] = true, -- Great Golden Kodo
        [ 323] = true, -- Turbostrider
        [ 324] = true, -- Swift Violet Ram
        [ 325] = true, -- Swift Purple Raptor
        [ 326] = true, -- White Skeletal Warhorse
        [ 327] = true, -- Swift Burgundy Wolf
        [ 328] = true, -- Magic Rooster
        [ 329] = true, -- Silver Covenant Hippogryph
        [ 330] = true, -- Sunreaver Dragonhawk
        [ 331] = true, -- Quel'dorei Steed
        [ 332] = true, -- Sunreaver Hawkstrider
        [ 333] = true, -- Magic Rooster
        [ 334] = true, -- Magic Rooster
        [ 335] = true, -- Magic Rooster
        [ 336] = true, -- Ochre Skeletal Warhorse
        [ 337] = true, -- Striped Dawnsaber
        [ 338] = true, -- Argent Charger
        [ 340] = true, -- Relentless Gladiator's Frost Wyrm
        [ 341] = true, -- Argent Warhorse
        [ 342] = true, -- Swift Horde Wolf
        [ 343] = true, -- Swift Alliance Steed
        [ 344] = true, -- Crusader's White Warhorse
        [ 345] = true, -- Crusader's Black Warhorse
        [ 349] = true, -- Onyxian Drake
        [ 350] = true, -- Sunwalker Kodo
        [ 351] = true, -- Great Sunwalker Kodo
        [ 352] = true, -- X-45 Heartbreaker
        [ 363] = true, -- Invincible
        [ 364] = true, -- Icebound Frostbrood Vanquisher
        [ 365] = true, -- Bloodbathed Frostbrood Vanquisher
        [ 366] = true, -- Crimson Deathcharger
        [ 367] = true, -- Exarch's Elekk
        [ 368] = true, -- Great Exarch's Elekk
        [ 371] = true, -- Blazing Hippogryph
        [ 372] = true, -- Wooly White Rhino
        [ 375] = true, -- Frosty Flying Carpet
        [ 376] = true, -- Celestial Steed
        [ 382] = true, -- X-53 Touring Rocket
        [1679] = true, -- Frostbrood Proto-Wyrm
    },

    [3] = { -- Cataclysm
        [ 358] = true, -- Wrathful Gladiator's Frost Wyrm
        [ 373] = true, -- Vashj'ir Seahorse
        [ 386] = true, -- Fossilized Raptor
        [ 388] = true, -- Goblin Trike
        [ 389] = true, -- Goblin Turbo-Trike
        [ 391] = true, -- Volcanic Stone Drake
        [ 392] = true, -- Drake of the East Wind
        [ 393] = true, -- Phosphorescent Stone Drake
        [ 394] = true, -- Drake of the West Wind
        [ 395] = true, -- Drake of the North Wind
        [ 396] = true, -- Drake of the South Wind
        [ 397] = true, -- Vitreous Stone Drake
        [ 398] = true, -- Brown Riding Camel
        [ 399] = true, -- Tan Riding Camel
        [ 400] = true, -- Grey Riding Camel
        [ 401] = true, -- Dark Phoenix
        [ 403] = true, -- Golden King
        [ 404] = true, -- Ultramarine Qiraji Battle Tank
        [ 405] = true, -- Spectral Steed
        [ 406] = true, -- Spectral Wolf
        [ 407] = true, -- Sandstone Drake
        [ 408] = true, -- Mottled Drake
        [ 409] = true, -- Kor'kron Annihilator
        [ 410] = true, -- Armored Razzashi Raptor
        [ 411] = true, -- Swift Zulian Panther
        [ 412] = true, -- Amani Dragonhawk
        [ 413] = true, -- Flameward Hippogryph
        [ 415] = true, -- Pureblood Fire Hawk
        [ 416] = true, -- Felfire Hawk
        [ 417] = true, -- Corrupted Fire Hawk
        [ 418] = true, -- Savage Raptor
        [ 419] = true, -- Amani Battle Bear
        [ 420] = true, -- Subdued Seahorse
        [ 421] = true, -- Winged Guardian
        [ 422] = true, -- Vicious War Steed
        [ 423] = true, -- Vicious War Wolf
        [ 424] = true, -- Vicious Gladiator's Twilight Drake
        [ 425] = true, -- Flametalon of Alysrazor
        [ 426] = true, -- Swift Shorestrider
        [ 428] = true, -- Ruthless Gladiator's Twilight Drake
        [ 429] = true, -- Swift Forest Strider
        [ 430] = true, -- Swift Springstrider
        [ 431] = true, -- Swift Lovebird
        [ 432] = true, -- White Riding Camel
        [ 433] = true, -- Corrupted Hippogryph
        [ 434] = true, -- Darkmoon Dancing Bear
        [ 435] = true, -- Mountain Horse
        [ 436] = true, -- Swift Mountain Horse
        [ 439] = true, -- Tyrael's Charger
        [ 440] = true, -- Spectral Gryphon
        [ 441] = true, -- Spectral Wind Rider
        [ 442] = true, -- Blazing Drake
        [ 443] = true, -- Twilight Harbinger
        [ 444] = true, -- Life-Binder's Handmaiden
        [ 445] = true, -- Experiment 12-B
        [ 446] = true, -- Heart of the Aspects
        [ 447] = true, -- Feldrake
        [1812] = true, -- Runebound Firelord
    },

    [4] = { -- Mists of Pandaria
        [ 448] = true, -- Jade Cloud Serpent
        [ 449] = true, -- Azure Water Strider
        [ 450] = true, -- Pandaren Kite
        [ 451] = true, -- Jeweled Onyx Panther
        [ 452] = true, -- Green Dragon Turtle
        [ 453] = true, -- Great Red Dragon Turtle
        [ 455] = true, -- Obsidian Nightwing
        [ 456] = true, -- Sapphire Panther
        [ 457] = true, -- Jade Panther
        [ 458] = true, -- Ruby Panther
        [ 459] = true, -- Sunstone Panther
        [ 460] = true, -- Grand Expedition Yak
        [ 462] = true, -- Kafa Yak
        [ 463] = true, -- Amber Scorpion
        [ 464] = true, -- Azure Cloud Serpent
        [ 465] = true, -- Golden Cloud Serpent
        [ 466] = true, -- Thundering Jade Cloud Serpent
        [ 467] = true, -- Cataclysmic Gladiator's Twilight Drake
        [ 468] = true, -- Imperial Quilen
        [ 469] = true, -- Depleted-Kyparium Rocket
        [ 470] = true, -- Geosynchronous World Spinner
        [ 471] = true, -- Onyx Cloud Serpent
        [ 472] = true, -- Crimson Cloud Serpent
        [ 473] = true, -- Heavenly Onyx Cloud Serpent
        [ 474] = true, -- Heavenly Crimson Cloud Serpent
        [ 475] = true, -- Heavenly Golden Cloud Serpent
        [ 477] = true, -- Heavenly Azure Cloud Serpent
        [ 478] = true, -- Astral Cloud Serpent
        [ 479] = true, -- Azure Riding Crane
        [ 480] = true, -- Golden Riding Crane
        [ 481] = true, -- Regal Riding Crane
        [ 482] = true, -- Jungle Riding Crane
        [ 484] = true, -- Black Riding Yak
        [ 485] = true, -- Modest Expedition Yak
        [ 486] = true, -- Grey Riding Yak
        [ 487] = true, -- Blonde Riding Yak
        [ 488] = true, -- Crimson Water Strider
        [ 492] = true, -- Black Dragon Turtle
        [ 493] = true, -- Blue Dragon Turtle
        [ 494] = true, -- Brown Dragon Turtle
        [ 495] = true, -- Purple Dragon Turtle
        [ 496] = true, -- Red Dragon Turtle
        [ 497] = true, -- Great Green Dragon Turtle
        [ 498] = true, -- Great Black Dragon Turtle
        [ 499] = true, -- Great Blue Dragon Turtle
        [ 500] = true, -- Great Brown Dragon Turtle
        [ 501] = true, -- Great Purple Dragon Turtle
        [ 503] = true, -- Crimson Pandaren Phoenix
        [ 504] = true, -- Thundering August Cloud Serpent
        [ 505] = true, -- Green Shado-Pan Riding Tiger
        [ 506] = true, -- Blue Shado-Pan Riding Tiger
        [ 507] = true, -- Red Shado-Pan Riding Tiger
        [ 508] = true, -- Brown Riding Goat
        [ 509] = true, -- Red Flying Cloud
        [ 510] = true, -- White Riding Goat
        [ 511] = true, -- Black Riding Goat
        [ 515] = true, -- Son of Galleon
        [ 516] = true, -- Pandaren Kite
        [ 517] = true, -- Thundering Ruby Cloud Serpent
        [ 518] = true, -- Ashen Pandaren Phoenix
        [ 519] = true, -- Emerald Pandaren Phoenix
        [ 520] = true, -- Violet Pandaren Phoenix
        [ 521] = true, -- Jade Pandaren Kite
        [ 522] = true, -- Sky Golem
        [ 523] = true, -- Swift Windsteed
        [ 526] = true, -- Grand Armored Gryphon
        [ 527] = true, -- Grand Armored Wyvern
        [ 528] = true, -- Grand Gryphon
        [ 529] = true, -- Grand Wyvern
        [ 530] = true, -- Armored Skyscreamer
        [ 531] = true, -- Spawn of Horridon
        [ 532] = true, -- Ghastly Charger
        [ 533] = true, -- Cobalt Primordial Direhorn
        [ 534] = true, -- Amber Primordial Direhorn
        [ 535] = true, -- Slate Primordial Direhorn
        [ 536] = true, -- Jade Primordial Direhorn
        [ 537] = true, -- Bone-White Primal Raptor
        [ 538] = true, -- Red Primal Raptor
        [ 539] = true, -- Black Primal Raptor
        [ 540] = true, -- Green Primal Raptor
        [ 541] = true, -- Malevolent Gladiator's Cloud Serpent
        [ 542] = true, -- Thundering Cobalt Cloud Serpent
        [ 543] = true, -- Clutch of Ji-Kun
        [ 544] = true, -- Armored Bloodwing
        [ 545] = true, -- Golden Primal Direhorn
        [ 546] = true, -- Crimson Primal Direhorn
        [ 547] = true, -- Hearthsteed
        [ 548] = true, -- Armored Red Dragonhawk
        [ 549] = true, -- Armored Blue Dragonhawk
        [ 550] = true, -- Brawler's Burly Mushan Beast
        [ 551] = true, -- Enchanted Fey Dragon
        [ 554] = true, -- Vicious Kaldorei Warsaber
        [ 555] = true, -- Vicious Skeletal Warhorse
        [ 557] = true, -- Spawn of Galakras
        [ 558] = true, -- Kor'kron War Wolf
        [ 559] = true, -- Kor'kron Juggernaut
        [ 560] = true, -- Ashhide Mushan Beast
        [ 561] = true, -- Thundering Onyx Cloud Serpent
        [ 562] = true, -- Tyrannical Gladiator's Cloud Serpent
        [ 563] = true, -- Grievous Gladiator's Cloud Serpent
        [ 564] = true, -- Prideful Gladiator's Cloud Serpent
        [ 568] = true, -- Emerald Hippogryph
        [ 571] = true, -- Iron Skyreaver
        [2476] = true, -- Sha-Warped Cloud Serpent
        [2477] = true, -- Sha-Warped Riding Tiger
        [2582] = true, -- Shaohao's Sage Serpent
    },

    [5] = { -- Warlords of Draenor
        [ 454] = true, -- Cindermane Charger
        [ 552] = true, -- Ironbound Wraithcharger
        [ 593] = true, -- Warforged Nightmare
        [ 594] = true, -- Grinning Reaver
        [ 600] = true, -- Dread Raven
        [ 603] = true, -- Creeping Carpet
        [ 606] = true, -- Core Hound
        [ 607] = true, -- Gorestrider Gronnling
        [ 608] = true, -- Witherhide Cliffstomper
        [ 609] = true, -- Trained Icehoof
        [ 611] = true, -- Tundra Icehoof
        [ 612] = true, -- Bloodhoof Bull
        [ 613] = true, -- Ironhoof Destroyer
        [ 614] = true, -- Mottled Meadowstomper
        [ 615] = true, -- Trained Meadowstomper
        [ 616] = true, -- Shadowhide Pearltusk
        [ 617] = true, -- Dusty Rockhide
        [ 618] = true, -- Armored Irontusk
        [ 619] = true, -- Blacksteel Battleboar
        [ 620] = true, -- Rocktusk Battleboar
        [ 621] = true, -- Armored Frostboar
        [ 622] = true, -- Armored Razorback
        [ 623] = true, -- Frostplains Battleboar
        [ 624] = true, -- Wild Goretusk
        [ 625] = true, -- Domesticated Razorback
        [ 626] = true, -- Giant Coldsnout
        [ 627] = true, -- Great Greytusk
        [ 628] = true, -- Trained Rocktusk
        [ 629] = true, -- Trained Riverwallow
        [ 630] = true, -- Sapphire Riverbeast
        [ 631] = true, -- Mudback Riverbeast
        [ 632] = true, -- Mosshide Riverwallow
        [ 634] = true, -- Solar Spirehawk
        [ 635] = true, -- Shadowmane Charger
        [ 636] = true, -- Swift Breezestrider
        [ 637] = true, -- Trained Silverpelt
        [ 638] = true, -- Breezestrider Stallion
        [ 639] = true, -- Pale Thorngrazer
        [ 640] = true, -- Vicious War Ram
        [ 641] = true, -- Vicious War Raptor
        [ 642] = true, -- Garn Steelmaw
        [ 643] = true, -- Warsong Direfang
        [ 644] = true, -- Armored Frostwolf
        [ 645] = true, -- Ironside Warwolf
        [ 646] = true, -- Coldflame Infernal
        [ 647] = true, -- Trained Snarler
        [ 648] = true, -- Swift Frostwolf
        [ 649] = true, -- Smoky Direwolf
        [ 650] = true, -- Dustmane Direwolf
        [ 651] = true, -- Warlord's Deathwheel
        [ 652] = true, -- Champion's Treadblade
        [ 654] = true, -- Challenger's War Yeti
        [ 655] = true, -- Sunhide Gronnling
        [ 657] = true, -- Garn Nighthowl
        [ 664] = true, -- Emerald Drake
        [ 678] = true, -- Chauffeured Mechano-Hog
        [ 679] = true, -- Chauffeured Mekgineer's Chopper
        [ 682] = true, -- Voidtalon of the Dark Star
        [ 741] = true, -- Mystic Runesaber
        [ 751] = true, -- Felsteel Annihilator
        [ 753] = true, -- Corrupted Dreadwing
        [ 755] = true, -- Vicious War Mechanostrider
        [ 756] = true, -- Vicious War Kodo
        [ 758] = true, -- Infernal Direwolf
        [ 759] = true, -- Primal Gladiator's Felblood Gronnling
        [ 760] = true, -- Wild Gladiator's Felblood Gronnling
        [ 761] = true, -- Warmongering Gladiator's Felblood Gronnling
        [ 762] = true, -- Coalfist Gronnling
        [ 764] = true, -- Grove Warden
        [ 765] = true, -- Bristling Hellboar
        [ 768] = true, -- Deathtusk Felboar
        [ 769] = true, -- Minion of Grumpus
        [ 772] = true, -- Soaring Skyterror
        [ 778] = true, -- Eclipse Dragonhawk
        [ 781] = true, -- Infinite Timereaver
    },

    [6] = { -- Legion
        [ 476] = true, -- Yu'lei, Daughter of Jade
        [ 633] = true, -- Hellfire Infernal
        [ 656] = true, -- Llothien Prowler
        [ 663] = true, -- Bloodfang Widow
        [ 763] = true, -- Illidari Felstalker
        [ 773] = true, -- Grove Defiler
        [ 775] = true, -- Prestigious War Steed
        [ 779] = true, -- Spirit of Eche'ro
        [ 780] = true, -- Felsaber
        [ 784] = true, -- Prestigious War Wolf
        [ 791] = true, -- Felblaze Infernal
        [ 793] = true, -- Predatory Bloodgazer
        [ 794] = true, -- Brilliant Direbeak
        [ 795] = true, -- Snowfeather Hunter
        [ 796] = true, -- Viridian Sharptalon
        [ 797] = true, -- Steelbound Devourer
        [ 800] = true, -- Brinedeep Bottom-Feeder
        [ 802] = true, -- Long-Forgotten Hippogryph
        [ 804] = true, -- Ratstallion
        [ 826] = true, -- Prestigious Bronze Courser
        [ 831] = true, -- Prestigious Royal Courser
        [ 832] = true, -- Prestigious Forest Courser
        [ 833] = true, -- Prestigious Ivory Courser
        [ 834] = true, -- Prestigious Azure Courser
        [ 836] = true, -- Prestigious Midnight Courser
        [ 838] = true, -- Fathom Dweller
        [ 841] = true, -- Vicious Gilnean Warhorse
        [ 842] = true, -- Vicious War Trike
        [ 843] = true, -- Vicious Warstrider
        [ 844] = true, -- Vicious War Elekk
        [ 845] = true, -- Mechanized Lumber Extractor
        [ 846] = true, -- Leyfeather Hippogryph
        [ 847] = true, -- Arcadian War Turtle
        [ 848] = true, -- Vindictive Gladiator's Storm Dragon
        [ 849] = true, -- Fearless Gladiator's Storm Dragon
        [ 850] = true, -- Cruel Gladiator's Storm Dragon
        [ 851] = true, -- Ferocious Gladiator's Storm Dragon
        [ 852] = true, -- Fierce Gladiator's Storm Dragon
        [ 853] = true, -- Dominant Gladiator's Storm Dragon
        [ 854] = true, -- Great Northern Elderhorn
        [ 855] = true, -- Darkwater Skate
        [ 860] = true, -- Archmage's Prismatic Disc
        [ 861] = true, -- High Priest's Lightsworn Seeker
        [ 864] = true, -- Ban-Lu, Grandmaster's Companion
        [ 865] = true, -- Huntmaster's Loyal Wolfhawk
        [ 866] = true, -- Deathlord's Vilebrood Vanquisher
        [ 867] = true, -- Battlelord's Bloodthirsty War Wyrm
        [ 868] = true, -- Slayer's Felbroken Shrieker
        [ 870] = true, -- Huntmaster's Fierce Wolfhawk
        [ 872] = true, -- Huntmaster's Dire Wolfhawk
        [ 873] = true, -- Vicious War Bear
        [ 874] = true, -- Vicious War Bear
        [ 875] = true, -- Midnight
        [ 876] = true, -- Vicious War Lion
        [ 877] = true, -- Ivory Hawkstrider
        [ 878] = true, -- Brawler's Burly Basilisk
        [ 881] = true, -- Arcanist's Manasaber
        [ 882] = true, -- Vicious War Scorpion
        [ 883] = true, -- Smoldering Ember Wyrm
        [ 884] = true, -- Shadowblade's Murderous Omen
        [ 885] = true, -- Highlord's Golden Charger
        [ 888] = true, -- Farseer's Raging Tempest
        [ 889] = true, -- Shadowblade's Lethal Omen
        [ 890] = true, -- Shadowblade's Baneful Omen
        [ 891] = true, -- Shadowblade's Crimson Omen
        [ 892] = true, -- Highlord's Vengeful Charger
        [ 893] = true, -- Highlord's Vigilant Charger
        [ 894] = true, -- Highlord's Valorous Charger
        [ 896] = true, -- Primal Flamesaber
        [ 898] = true, -- Netherlord's Chaotic Wrathsteed
        [ 899] = true, -- Abyss Worm
        [ 900] = true, -- Vicious War Turtle
        [ 901] = true, -- Vicious War Turtle
        [ 905] = true, -- Leywoven Flying Carpet
        [ 906] = true, -- Darkspore Mana Ray
        [ 930] = true, -- Netherlord's Brimstone Wrathsteed
        [ 931] = true, -- Netherlord's Accursed Wrathsteed
        [ 932] = true, -- Lightforged Warframe
        [ 935] = true, -- Blue Qiraji War Tank
        [ 936] = true, -- Red Qiraji War Tank
        [ 937] = true, -- Black Qiraji War Tank
        [ 939] = true, -- Sable Ruinstrider
        [ 941] = true, -- Highmountain Elderhorn
        [ 942] = true, -- Wild Dreamrunner
        [ 943] = true, -- Cloudwing Hippogryph
        [ 944] = true, -- Valarjar Stormwing
        [ 945] = true, -- Vicious War Fox
        [ 946] = true, -- Vicious War Fox
        [ 947] = true, -- Riddler's Mind-Worm
        [ 948] = true, -- Demonic Gladiator's Storm Dragon
        [ 949] = true, -- Luminous Starseeker
        [ 954] = true, -- Shackled Ur'zul
        [ 955] = true, -- Vile Fiend
        [ 959] = true, -- Stormwind Skychaser
        [ 960] = true, -- Orgrimmar Interceptor
        [ 961] = true, -- Lucid Nightmare
        [ 962] = true, -- Darkmoon Dirigible
        [ 964] = true, -- Amethyst Ruinstrider
        [ 965] = true, -- Cerulean Ruinstrider
        [ 966] = true, -- Beryl Ruinstrider
        [ 967] = true, -- Umber Ruinstrider
        [ 968] = true, -- Russet Ruinstrider
        [ 970] = true, -- Maddened Chaosrunner
        [ 971] = true, -- Antoran Charhound
        [ 972] = true, -- Antoran Gloomhound
        [ 973] = true, -- Lambent Mana Ray
        [ 974] = true, -- Vibrant Mana Ray
        [ 975] = true, -- Felglow Mana Ray
        [ 976] = true, -- Scintillating Mana Ray
        [ 978] = true, -- Violet Spellwing
        [ 979] = true, -- Crimson Slavermaw
        [ 980] = true, -- Acid Belcher
        [ 981] = true, -- Biletooth Gnasher
        [ 982] = true, -- Pond Nettle
        [ 983] = true, -- Glorious Felcrusher
        [ 984] = true, -- Blessed Felcrusher
        [ 985] = true, -- Avenging Felcrusher
        [ 986] = true, -- Bleakhoof Ruinstrider
        [1006] = true, -- Lightforged Felcrusher
        [1007] = true, -- Highmountain Thunderhoof
        [1008] = true, -- Nightborne Manasaber
        [1009] = true, -- Starcursed Voidstrider
        [1011] = true, -- Shu-Zen, the Divine Sentinel
    },

    [7] = { -- Battle for Azeroth
        [ 926] = true, -- Alabaster Hyena
        [ 928] = true, -- Dune Scavenger
        [ 933] = true, -- Obsidian Krolusk
        [ 956] = true, -- Leaping Veinseeker
        [ 958] = true, -- Spectral Pterrorwing
        [ 963] = true, -- Bloodgorged Crawg
        [ 993] = true, -- Squawks
        [ 994] = true, -- Royal Seafeather
        [ 995] = true, -- Sharkbait
        [ 996] = true, -- Seabraid Stallion
        [ 997] = true, -- Gilded Ravasaur
        [ 999] = true, -- Xiwyllag ATV
        [1010] = true, -- Admiralty Stallion
        [1012] = true, -- Green Marsh Hopper
        [1013] = true, -- Honeyback Harvester
        [1015] = true, -- Dapple Gray
        [1016] = true, -- Smoky Charger
        [1018] = true, -- Terrified Pack Mule
        [1019] = true, -- Goldenmane
        [1025] = true, -- The Hivemind
        [1026] = true, -- Vicious War Basilisk
        [1027] = true, -- Vicious War Basilisk
        [1028] = true, -- Mecha-Mogul Mk2
        [1030] = true, -- Dread Gladiator's Proto-Drake
        [1031] = true, -- Sinister Gladiator's Proto-Drake
        [1032] = true, -- Notorious Gladiator's Proto-Drake
        [1035] = true, -- Corrupted Gladiator's Proto-Drake
        [1038] = true, -- Zandalari Direhorn
        [1039] = true, -- Mighty Caravan Brutosaur
        [1040] = true, -- Tomb Stalker
        [1042] = true, -- Siltwing Albatross
        [1043] = true, -- Kua'fon
        [1044] = true, -- Mag'har Direwolf
        [1045] = true, -- Vicious War Clefthoof
        [1046] = true, -- Darkforge Ram
        [1047] = true, -- Dawnforge Ram
        [1048] = true, -- Dark Iron Core Hound
        [1049] = true, -- Undercity Plaguebat
        [1050] = true, -- Vicious War Riverbeast
        [1051] = true, -- The Dreadwake
        [1053] = true, -- Underrot Crawg
        [1054] = true, -- Teldrassil Hippogryph
        [1057] = true, -- Nazjatar Blood Serpent
        [1058] = true, -- Cobalt Pterrordax
        [1059] = true, -- Captured Swampstalker
        [1060] = true, -- Voldunai Dunescraper
        [1061] = true, -- Expedition Bloodswarmer
        [1062] = true, -- Dusky Waycrest Gryphon
        [1063] = true, -- Stormsong Coastwatcher
        [1064] = true, -- Proudmoore Sea Scout
        [1166] = true, -- Great Sea Ray
        [1167] = true, -- Frostshard Infernal
        [1168] = true, -- Fiery Hearthsteed
        [1169] = true, -- Surf Jelly
        [1172] = true, -- Conqueror's Scythemaw
        [1173] = true, -- Broken Highland Mustang
        [1174] = true, -- Highland Mustang
        [1175] = true, -- Twilight Avenger
        [1176] = true, -- Craghorn Chasm-Leaper
        [1178] = true, -- Qinsho's Eternal Hound
        [1179] = true, -- Palehide Direhorn
        [1180] = true, -- Swift Albino Raptor
        [1182] = true, -- Lil' Donkey
        [1183] = true, -- Skullripper
        [1185] = true, -- Witherbark Direwing
        [1190] = true, -- Pureheart Courser
        [1191] = true, -- Frenzied Feltalon
        [1192] = true, -- Prestigious Bloodforged Courser
        [1193] = true, -- Meat Wagon
        [1194] = true, -- Vicious White Warsaber
        [1195] = true, -- Vicious Black Warsaber
        [1196] = true, -- Vicious Black Bonesteed
        [1197] = true, -- Vicious White Bonesteed
        [1198] = true, -- Kul Tiran Charger
        [1199] = true, -- Blackpaw
        [1200] = true, -- Ashenvale Chimaera
        [1201] = true, -- Frightened Kodo
        [1203] = true, -- Umber Nightsaber
        [1204] = true, -- Sandy Nightsaber
        [1205] = true, -- Kaldorei Nightsaber
        [1206] = true, -- Blue Marsh Hopper
        [1207] = true, -- Yellow Marsh Hopper
        [1208] = true, -- Saltwater Seahorse
        [1209] = true, -- Stonehide Elderhorn
        [1210] = true, -- Bloodthirsty Dreadwing
        [1211] = true, -- Bloodgorged Hunter
        [1212] = true, -- Island Thunderscale
        [1213] = true, -- Risen Mare
        [1214] = true, -- Azureshell Krolusk
        [1215] = true, -- Rubyshell Krolusk
        [1216] = true, -- Priestess' Moonsaber
        [1217] = true, -- G.M.O.D.
        [1218] = true, -- Dazar'alor Windreaver
        [1219] = true, -- Glacial Tidestorm
        [1220] = true, -- Bruce
        [1221] = true, -- Hogrus, Swine of Good Fortune
        [1222] = true, -- Vulpine Familiar
        [1223] = true, -- Sylverian Dreamer
        [1224] = true, -- Wonderwing 2.0
        [1225] = true, -- Crusader's Direhorn
        [1227] = true, -- Aerial Unit R-21/X
        [1229] = true, -- Rusty Mechanocrawler
        [1230] = true, -- Unshackled Waveray
        [1231] = true, -- Ankoan Waveray
        [1232] = true, -- Azshari Bloatray
        [1237] = true, -- Royal Snapdragon
        [1238] = true, -- Snapback Scuttler
        [1239] = true, -- X-995 Mechanocat
        [1240] = true, -- Obsidian Worldbreaker
        [1242] = true, -- Beastlord's Irontusk
        [1243] = true, -- Beastlord's Warwolf
        [1245] = true, -- Bloodflank Charger
        [1246] = true, -- Ironclad Frostclaw
        [1247] = true, -- Mechacycle Model W
        [1248] = true, -- Junkheap Drifter
        [1249] = true, -- Child of Torcali
        [1250] = true, -- Mollie
        [1252] = true, -- Mechagon Peacekeeper
        [1253] = true, -- Scrapforged Mechaspider
        [1254] = true, -- Rustbolt Resistor
        [1255] = true, -- Deepcoral Snapdragon
        [1256] = true, -- Snapdragon Kelpstalker
        [1257] = true, -- Silent Glider
        [1258] = true, -- Fabious
        [1259] = true, -- Silver Tidestallion
        [1260] = true, -- Crimson Tidestallion
        [1262] = true, -- Inkscale Deepseeker
        [1265] = true, -- Uncorrupted Voidwing
        [1269] = true, -- Swift Spectral Fathom Ray
        [1277] = true, -- Honeyback Hivemother
        [1282] = true, -- Black Serpent of N'Zoth
        [1283] = true, -- Mechagon Mechanostrider
        [1285] = true, -- Frostwolf Snarler
        [1286] = true, -- Caravan Hyena
        [1287] = true, -- Explorer's Jungle Hopper
        [1288] = true, -- Explorer's Dunetrekker
        [1290] = true, -- Squeakers, the Trickster
        [1291] = true, -- Lucky Yun
        [1292] = true, -- Stormpike Battle Ram
        [1293] = true, -- Ny'alotha Allseer
        [1297] = true, -- Clutch of Ha-Li
        [1311] = true, -- Ivory Cloud Serpent
        [1312] = true, -- Gargantuan Grrloc
        [1313] = true, -- Rajani Warserpent
        [1314] = true, -- Drake of the Four Winds
        [1315] = true, -- Mail Muncher
        [1317] = true, -- Waste Marauder
        [1318] = true, -- Wastewander Skyterror
        [1319] = true, -- Malevolent Drone
        [1320] = true, -- Shadowbarb Drone
        [1321] = true, -- Wicked Swarmer
        [1322] = true, -- Wriggling Parasite
        [1324] = true, -- Elusive Quickhoof
        [1326] = true, -- Awakened Mindborer
        [1327] = true, -- Ren's Stalwart Hound
        [1328] = true, -- Xinlao
        [1329] = true, -- Springfur Alpaca
        [1346] = true, -- Steamscale Incinerator
    },

    [8] = { -- Shadowlands
        [ 803] = true, -- Mastercraft Gravewing
        [1289] = true, -- Ensorcelled Everwyrm
        [1298] = true, -- Hopecrusher Gargon
        [1299] = true, -- Battle Gargon Vrednic
        [1302] = true, -- Dreamlight Runestag
        [1303] = true, -- Enchanted Dreamlight Runestag
        [1304] = true, -- Mawsworn Soulhunter
        [1305] = true, -- Darkwarren Hardshell
        [1306] = true, -- Swift Gloomhoof
        [1307] = true, -- Sundancer
        [1309] = true, -- Chittering Animite
        [1310] = true, -- Horrid Dredwing
        [1330] = true, -- Sunwarmed Furline
        [1332] = true, -- Silky Shimmermoth
        [1350] = true, -- Colossal Slaughterclaw
        [1351] = true, -- Vicious War Spider
        [1352] = true, -- Vicious War Spider
        [1354] = true, -- Shadeleaf Runestag
        [1355] = true, -- Wakener's Runestag
        [1356] = true, -- Winterborn Runestag
        [1357] = true, -- Enchanted Shadeleaf Runestag
        [1358] = true, -- Enchanted Wakener's Runestag
        [1359] = true, -- Enchanted Winterborn Runestag
        [1360] = true, -- Shimmermist Runner
        [1361] = true, -- Duskflutter Ardenmoth
        [1362] = true, -- Spinemaw Gladechewer
        [1363] = true, -- Sinful Gladiator's Soul Eater
        [1364] = true, -- War-Bred Tauralus
        [1365] = true, -- Plaguerot Tauralus
        [1366] = true, -- Bonehoof Tauralus
        [1367] = true, -- Chosen Tauralus
        [1368] = true, -- Armored War-Bred Tauralus
        [1369] = true, -- Armored Plaguerot Tauralus
        [1370] = true, -- Armored Bonehoof Tauralus
        [1371] = true, -- Armored Chosen Tauralus
        [1372] = true, -- Blisterback Bloodtusk
        [1373] = true, -- Gorespine
        [1375] = true, -- Lurid Bloodtusk
        [1376] = true, -- Silvertip Dredwing
        [1377] = true, -- Rampart Screecher
        [1378] = true, -- Harvester's Dredwing
        [1379] = true, -- Endmire Flyer
        [1382] = true, -- Inquisition Gargon
        [1384] = true, -- Sinfall Gargon
        [1385] = true, -- Crypt Gargon
        [1387] = true, -- Desire's Battle Gargon
        [1388] = true, -- Gravestone Battle Gargon
        [1389] = true, -- Battle Gargon Silessa
        [1391] = true, -- Loyal Gorger
        [1392] = true, -- Pale Acidmaw
        [1393] = true, -- Wild Glimmerfur Prowler
        [1394] = true, -- Phalynx of Loyalty
        [1395] = true, -- Phalynx of Humility
        [1396] = true, -- Phalynx of Courage
        [1397] = true, -- Wildseed Cradle
        [1398] = true, -- Phalynx of Purity
        [1399] = true, -- Eternal Phalynx of Purity
        [1400] = true, -- Eternal Phalynx of Courage
        [1401] = true, -- Eternal Phalynx of Loyalty
        [1402] = true, -- Eternal Phalynx of Humility
        [1404] = true, -- Silverwind Larion
        [1405] = true, -- Restoration Deathwalker
        [1406] = true, -- Marrowfang
        [1407] = true, -- Callow Flayedwing
        [1408] = true, -- Gruesome Flayedwing
        [1409] = true, -- Bonesewn Fleshroc
        [1410] = true, -- Hulking Deathroc
        [1411] = true, -- Predatory Plagueroc
        [1413] = true, -- Dauntless Duskrunner
        [1414] = true, -- Sinrunner Blanchy
        [1415] = true, -- Arboreal Gulper
        [1416] = true, -- Mawsworn Charger
        [1417] = true, -- Hand of Hrestimorak
        [1419] = true, -- Sintouched Deathwalker
        [1420] = true, -- Umbral Scythehorn
        [1421] = true, -- Court Sinrunner
        [1422] = true, -- Warstitched Darkhound
        [1423] = true, -- Highwind Darkmane
        [1424] = true, -- Snowstorm
        [1425] = true, -- Gilded Prowler
        [1426] = true, -- Ascended Skymane
        [1428] = true, -- Amber Ardenmoth
        [1429] = true, -- Vibrant Flutterwing
        [1430] = true, -- Desertwing Hunter
        [1431] = true, -- Pale Regal Cervid
        [1433] = true, -- Vespoid Flutterer
        [1434] = true, -- Deepstar Aurelid
        [1436] = true, -- Battle-Hardened Aquilon
        [1437] = true, -- Battle-Bound Warhound
        [1438] = true, -- Bulbous Necroray
        [1439] = true, -- Infested Necroray
        [1440] = true, -- Pestilent Necroray
        [1441] = true, -- Bound Shadehound
        [1442] = true, -- Corridor Creeper
        [1443] = true, -- Voracious Gorger
        [1444] = true, -- Viridian Phase-Hunter
        [1445] = true, -- Slime Serpent
        [1446] = true, -- Tazavesh Gearglider
        [1448] = true, -- Serenade
        [1449] = true, -- Lord of the Corpseflies
        [1450] = true, -- Soaring Razorwing
        [1451] = true, -- Vicious War Croaker
        [1452] = true, -- Vicious War Croaker
        [1454] = true, -- Tamed Mauler
        [1455] = true, -- Beryl Shardhide
        [1456] = true, -- Sapphire Skyblazer
        [1458] = true, -- Wandering Ancient
        [1459] = true, -- Vicious War Gorm
        [1460] = true, -- Vicious War Gorm
        [1465] = true, -- Vicious Warstalker
        [1466] = true, -- Vicious Warstalker
        [1467] = true, -- Noble Bruffalon
        [1471] = true, -- Vengeance
        [1474] = true, -- Bestowed Thunderspine Packleader
        [1475] = true, -- Hand of Bahmethra
        [1476] = true, -- Wild Hunt Legsplitter
        [1477] = true, -- Undying Darkhound
        [1480] = true, -- Unchained Gladiator's Soul Eater
        [1481] = true, -- Cartel Master's Gearglider
        [1482] = true, -- Xy Trustee's Gearglider
        [1483] = true, -- Vandal's Gearglider
        [1484] = true, -- Ardenweald Wilderling
        [1485] = true, -- Autumnal Wilderling
        [1486] = true, -- Winter Wilderling
        [1487] = true, -- Summer Wilderling
        [1489] = true, -- Obsidian Gravewing
        [1490] = true, -- Sinfall Gravewing
        [1491] = true, -- Pale Gravewing
        [1492] = true, -- Elysian Aquilon
        [1493] = true, -- Forsworn Aquilon
        [1494] = true, -- Ascendant's Aquilon
        [1495] = true, -- Maldraxxian Corpsefly
        [1496] = true, -- Regal Corpsefly
        [1497] = true, -- Battlefield Swarmer
        [1500] = true, -- Sanctum Gloomcharger
        [1501] = true, -- Soulbound Gloomcharger
        [1502] = true, -- Fallen Charger
        [1503] = true, -- Hand of Nilganihmaht
        [1504] = true, -- Hand of Salaranga
        [1505] = true, -- Amber Shardhide
        [1506] = true, -- Crimson Shardhide
        [1507] = true, -- Darkmaul
        [1508] = true, -- Fierce Razorwing
        [1509] = true, -- Garnet Razorwing
        [1510] = true, -- Dusklight Razorwing
        [1511] = true, -- Maelie, the Wanderer
        [1513] = true, -- Sarge's Tale
        [1514] = true, -- Rampaging Mauler
        [1517] = true, -- Bound Blizzard
        [1520] = true, -- Soultwisted Deathwalker
        [1521] = true, -- Val'sharah Hippogryph
        [1522] = true, -- Heartlight Vombata
        [1523] = true, -- Curious Crystalsniffer
        [1524] = true, -- Darkened Vombata
        [1525] = true, -- Adorned Vombata
        [1526] = true, -- Deathrunner
        [1528] = true, -- Sundered Zerethsteed
        [1529] = true, -- Anointed Protostag
        [1531] = true, -- Wen Lo, the River's Edge
        [1532] = true, -- Soaring Spelltome
        [1533] = true, -- Forged Spiteflyer
        [1534] = true, -- Buzz
        [1535] = true, -- Bronzewing Vespoid
        [1536] = true, -- Mawdapted Raptora
        [1537] = true, -- Raptora Swooper
        [1538] = true, -- Bronze Helicid
        [1539] = true, -- Unsuccessful Prototype Fleetpod
        [1540] = true, -- Scarlet Helicid
        [1541] = true, -- Genesis Crawler
        [1542] = true, -- Tarachnid Creeper
        [1543] = true, -- Ineffable Skitterer
        [1544] = true, -- Wastewarped Deathwalker
        [1547] = true, -- Goldplate Bufonid
        [1549] = true, -- Shimmering Aurelid
        [1551] = true, -- Cryptic Aurelid
        [1552] = true, -- Carcinized Zerethsteed
        [1564] = true, -- Colossal Soulshredder Mawrat
        [1565] = true, -- Colossal Umbrahide Mawrat
        [1566] = true, -- Colossal Ebonclaw Mawrat
        [1568] = true, -- Lightforged Ruinstrider
        [1569] = true, -- Patient Bufonid
        [1570] = true, -- Prototype Leaper
        [1571] = true, -- Russet Bufonid
        [1572] = true, -- Cosmic Gladiator's Soul Eater
        [1576] = true, -- Jigglesworth Sr.
        [1580] = true, -- Heartbond Lupine
        [1581] = true, -- Nether-Gorged Greatwyrm
        [1584] = true, -- Colossal Plaguespew Mawrat
        [1585] = true, -- Colossal Wraithbound Mawrat
        [1587] = true, -- Zereth Overseer
        [1597] = true, -- Grimhowl
        [1599] = true, -- Eternal Gladiator's Soul Eater
        [1600] = true, -- Elusive Emerald Hawkstrider
        [1602] = true, -- Tuskarr Shoreglider
    },

    [9] = { -- Dragonflight
        [ 799] = true, -- Flarecore Infernal
        [1266] = true, -- Alabaster Stormtalon
        [1267] = true, -- Alabaster Thunderwing
        [1468] = true, -- Amber Skitterfly
        [1469] = true, -- Magmashell
        [1478] = true, -- Skyskin Hornstrider
        [1545] = true, -- Divine Kiss of Ohn'ahra
        [1546] = true, -- Iskaara Trader's Ottuk
        [1553] = true, -- Liberated Slyvern
        [1556] = true, -- Tangled Dreamweaver
        [1563] = true, -- Highland Drake
        [1573] = true, -- Magenta Cloud Serpent
        [1574] = true, -- Crusty Crawler
        [1575] = true, -- Quawks
        [1577] = true, -- Ash'adar, Harbinger of Dawn
        [1579] = true, -- Coral-Stalker Waveray
        [1582] = true, -- Savage Green Battle Turtle
        [1583] = true, -- Armored Siege Kodo
        [1586] = true, -- Armored Golden Pterrordax
        [1588] = true, -- Winding Slitherdrake
        [1589] = true, -- Renewed Proto-Drake
        [1590] = true, -- Windborne Velocidrake
        [1591] = true, -- Cliffside Wylderdrake
        [1594] = true, -- Jade, Bright Foreseer
        [1595] = true, -- Cerulean Marsh Hopper
        [1596] = true, -- Amalgam of Rage
        [1603] = true, -- Subterranean Magmammoth
        [1612] = true, -- Loyal Magmammoth
        [1614] = true, -- Stormtouched Bruffalon
        [1615] = true, -- Tamed Skitterfly
        [1616] = true, -- Azure Skitterfly
        [1617] = true, -- Verdant Skitterfly
        [1618] = true, -- Bestowed Sandskimmer
        [1619] = true, -- Ancient Salamanther
        [1621] = true, -- Coralscale Salamanther
        [1622] = true, -- Stormhide Salamanther
        [1623] = true, -- Seething Slug
        [1626] = true, -- Shellack
        [1627] = true, -- Gooey Snailemental
        [1629] = true, -- Scrappy Worldsnail
        [1633] = true, -- Bestowed Trawling Mammoth
        [1634] = true, -- Mossy Mammoth
        [1635] = true, -- Plainswalker Bearer
        [1638] = true, -- Explorer's Stonehide Packbeast
        [1639] = true, -- Lizi, Thunderspine Tramper
        [1644] = true, -- Raging Magmammoth
        [1645] = true, -- Renewed Magmammoth
        [1651] = true, -- Bestowed Ottuk Vanguard
        [1653] = true, -- Brown War Ottuk
        [1654] = true, -- Otterworldly Ottuk Carrier
        [1655] = true, -- Yellow War Ottuk
        [1656] = true, -- Otto
        [1657] = true, -- Brown Scouting Ottuk
        [1658] = true, -- Ivory Trader's Ottuk
        [1659] = true, -- Yellow Scouting Ottuk
        [1660] = true, -- Crimson Gladiator's Drake
        [1662] = true, -- Telix the Stormhorn
        [1664] = true, -- Guardian Vorquin
        [1665] = true, -- Swift Armored Vorquin
        [1667] = true, -- Armored Vorquin Leystrider
        [1668] = true, -- Majestic Armored Vorquin
        [1669] = true, -- Bestowed Ohuna Spotter
        [1671] = true, -- Duskwing Ohuna
        [1672] = true, -- Zenet Hatchling
        [1674] = true, -- Temperamental Skyclaw
        [1681] = true, -- Hailstorm Armoredon
        [1683] = true, -- Crimson Vorquin
        [1684] = true, -- Sapphire Vorquin
        [1685] = true, -- Bronze Vorquin
        [1686] = true, -- Obsidian Vorquin
        [1688] = true, -- Vicious Sabertooth
        [1689] = true, -- Vicious Sabertooth
        [1692] = true, -- Wondrous Wavewhisker
        [1698] = true, -- Rocket Shredder 9001
        [1699] = true, -- Gleaming Moonbeast
        [1725] = true, -- Inferno Armoredon
        [1727] = true, -- Tarecgosa's Visage
        [1729] = true, -- Big Slick in the City
        [1730] = true, -- Igneous Shalewing
        [1732] = true, -- Cobalt Shalewing
        [1733] = true, -- Calescent Shalewing
        [1734] = true, -- Shadowflame Shalewing
        [1735] = true, -- Cataloged Shalewing
        [1736] = true, -- Boulder Hauler
        [1737] = true, -- Sandy Shalewing
        [1738] = true, -- Morsel Sniffer
        [1739] = true, -- Obsidian Gladiator's Slitherdrake
        [1740] = true, -- Vicious War Snail
        [1741] = true, -- Vicious War Snail
        [1742] = true, -- Felcrystal Scorpion
        [1744] = true, -- Grotto Netherwing Drake
        [1772] = true, -- Scarlet Pterrordax
        [1773] = true, -- Harbor Gryphon
        [1774] = true, -- Valiance
        [1776] = true, -- White War Wolf
        [1777] = true, -- Ravenous Black Gryphon
        [1778] = true, -- Gold-Toed Albatross
        [1779] = true, -- Felstorm Dragon
        [1781] = true, -- Sulfur Hound
        [1782] = true, -- Perfected Juggernaut
        [1783] = true, -- Scourgebound Vanquisher
        [1784] = true, -- Royal Swarmer
        [1785] = true, -- Ancestral Clefthoof
        [1794] = true, -- Pattie
        [1795] = true, -- Auspicious Arborwyrm
        [1797] = true, -- Ginormous Grrloc
        [1798] = true, -- Azure Worldchiller
        [1799] = true, -- Eve's Ghastly Rider
        [1801] = true, -- Verdant Armoredon
        [1808] = true, -- Blossoming Dreamstag
        [1809] = true, -- Suntouched Dreamstag
        [1810] = true, -- Rekindled Dreamstag
        [1811] = true, -- Lunar Dreamstag
        [1813] = true, -- Mimiron's Jumpjets
        [1814] = true, -- Shadow Dusk Dreamsaber
        [1815] = true, -- Winter Night Dreamsaber
        [1816] = true, -- Evening Sun Dreamsaber
        [1817] = true, -- Morning Flourish Dreamsaber
        [1818] = true, -- Anu'relos, Flame's Guidance
        [1819] = true, -- Vicious Moonbeast
        [1820] = true, -- Vicious Moonbeast
        [1822] = true, -- Draconic Gladiator's Drake
        [1824] = true, -- Brown-Furred Spiky Bakar
        [1825] = true, -- Taivan
        [1830] = true, -- Flourishing Whimsydrake
        [1831] = true, -- Verdant Gladiator's Slitherdrake
        [1833] = true, -- Springtide Dreamtalon
        [1834] = true, -- Ochre Dreamtalon
        [1835] = true, -- Snowfluff Dreamtalon
        [1837] = true, -- Delugen
        [1838] = true, -- Talont
        [1839] = true, -- Stargrazer
        [1841] = true, -- Crimson Glimmerfur
        [1938] = true, -- Mammyth
        [1939] = true, -- Imagiwing
        [1940] = true, -- Salatrancer
        [1941] = true, -- Heartseeker Mana Ray
        [1942] = true, -- Jeweled Copper Scarab
        [1943] = true, -- Incognitro, the Indecipherable Felcycle
        [1944] = true, -- Golden Regal Scarab
        [1947] = true, -- Hateforged Blazecycle
        [1948] = true, -- Voidfire Deathcycle
        [1949] = true, -- Gilnean Prowler
        [1956] = true, -- Fur-endship Fox
        [1957] = true, -- Soaring Sky Fox
        [1958] = true, -- Twilight Sky Prowler
        [1959] = true, -- Compass Rose
        [2023] = true, -- Noble Flying Carpet
        [2035] = true, -- Majestic Azure Peafowl
        [2036] = true, -- Brilliant Sunburst Peafowl
        [2038] = true, -- Clayscale Hornstrider
        [2039] = true, -- Savage Blue Battle Turtle
        [2055] = true, -- Infinite Armoredon
        [2056] = true, -- Vicious Dreamtalon
        [2057] = true, -- Vicious Dreamtalon
        [2060] = true, -- Golden Discus
        [2063] = true, -- Mogu Hazeblazer
        [2064] = true, -- Sky Surfer
        [2065] = true, -- Daystorm Windsteed
        [2067] = true, -- Forest Windsteed
        [2068] = true, -- Dashing Windsteed
        [2069] = true, -- Feathered Windsurfer
        [2070] = true, -- Guardian Quilen
        [2071] = true, -- Marble Quilen
        [2072] = true, -- Gilded Riding Crane
        [2073] = true, -- Pale Riding Crane
        [2074] = true, -- Rose Riding Crane
        [2075] = true, -- Silver Riding Crane
        [2076] = true, -- Luxurious Riding Crane
        [2077] = true, -- Tropical Riding Crane
        [2078] = true, -- Snowy Riding Goat
        [2080] = true, -- Little Red Riding Goat
        [2081] = true, -- Bloody Skyscreamer
        [2083] = true, -- Night Pterrorwing
        [2084] = true, -- Jade Pterrordax
        [2085] = true, -- Cobalt Juggernaut
        [2086] = true, -- Fel Iron Juggernaut
        [2087] = true, -- Purple Shado-Pan Riding Tiger
        [2088] = true, -- Riverwalker Mushan
        [2089] = true, -- Palehide Mushan Beast
        [2090] = true, -- Polly Roger
        [2091] = true, -- Voyaging Wilderling
        [2114] = true, -- Zovaal's Soul Eater
        [2118] = true, -- Amber Pterrordax
        [2140] = true, -- Charming Courier
        [2142] = true, -- August Phoenix
        [2143] = true, -- Astral Emperor's Serpent
        [2152] = true, -- Pearlescent Goblin Wave Shredder
        [2189] = true, -- Underlight Corrupted Behemoth
    },

    [10] = { -- The War Within
        [1374] = true, -- Bonecleaver's Skullboar
        [1550] = true, -- Depthstalker
        [1792] = true, -- Algarian Stormrider
        [1945] = true, -- Jeweled Sapphire Scarab
        [2116] = true, -- Remembered Golden Gryphon
        [2117] = true, -- Remembered Wind Rider
        [2119] = true, -- Stonevault Mechsuit
        [2144] = true, -- Delver's Dirigible
        [2145] = true, -- Kickin' Kezan Waveshredder
        [2148] = true, -- Smoldering Cinderbee
        [2150] = true, -- Vicious Skyflayer
        [2158] = true, -- Crowd Pummeler 2-30
        [2159] = true, -- Machine Defense Unit 1-11
        [2162] = true, -- Cyan Glowmite
        [2165] = true, -- Soaring Meaderbee
        [2167] = true, -- Raging Cinderbee
        [2171] = true, -- Widow's Undercrawler
        [2172] = true, -- Heritage Undercrawler
        [2174] = true, -- Royal Court Undercrawler
        [2176] = true, -- Alunira
        [2177] = true, -- Aquamarine Swarmite
        [2178] = true, -- Nesting Swarmite
        [2180] = true, -- Shadowed Swarmite
        [2181] = true, -- Swarmite Skyhunter
        [2184] = true, -- Ferocious Jawcrawler
        [2188] = true, -- Kah, Legend of the Deep
        [2190] = true, -- Shadow of Doubt
        [2191] = true, -- Shackled Shadow
        [2192] = true, -- Beledar's Spawn
        [2193] = true, -- Vermillion Imperial Lynx
        [2194] = true, -- Dauntless Imperial Lynx
        [2198] = true, -- Kor'kron Warsaber
        [2199] = true, -- Blackrock Warsaber
        [2201] = true, -- Sentinel War Wolf
        [2203] = true, -- Kaldorei War Wolf
        [2204] = true, -- Wick
        [2205] = true, -- Ol' Mole Rufus
        [2209] = true, -- Crimson Mudnose
        [2211] = true, -- Vicious Skyflayer
        [2213] = true, -- Shale Ramolith
        [2214] = true, -- Slatestone Ramolith
        [2218] = true, -- Forged Gladiator's Fel Bat
        [2219] = true, -- Sureki Skyrazor
        [2220] = true, -- Retrained Skyrazor
        [2222] = true, -- Siesbarg
        [2223] = true, -- Ascendant Skyrazor
        [2224] = true, -- Frayfeather Hippogryph
        [2225] = true, -- Amani Hunting Bear
        [2230] = true, -- Ivory Goliathus
        [2232] = true, -- Savage Ebony Battle Turtle
        [2233] = true, -- Earthen Ordinant's Ramolith
        [2235] = true, -- Startouched Furline
        [2237] = true, -- Grizzly Hills Packmaster
        [2238] = true, -- Plunderlord's Golden Crocolisk
        [2239] = true, -- Keg Leg's Radiant Crocolisk
        [2240] = true, -- Plunderlord's Midnight Crocolisk
        [2244] = true, -- Diamond Mechsuit
        [2249] = true, -- Hand of Reshkigaal
        [2255] = true, -- Golden Ashes of Al'ar
        [2259] = true, -- Gigantic Grrloc
        [2261] = true, -- Coldflame Tempest
        [2265] = true, -- Trader's Gilded Brutosaur
        [2272] = true, -- Crimson Armored Growler
        [2274] = true, -- Blackwater Bonecrusher
        [2276] = true, -- Darkfuse Chompactor
        [2277] = true, -- Violet Armored Growler
        [2278] = true, -- Flarendo the Furious
        [2279] = true, -- Thunderdrum Misfire
        [2280] = true, -- The Topskimmer Special
        [2281] = true, -- Steamwheedle Supplier
        [2283] = true, -- Innovation Investigator
        [2284] = true, -- Ochre Delivery Rocket
        [2286] = true, -- Blackwater Shredder Deluxe Mk 2
        [2287] = true, -- Darkfuse Demolisher
        [2288] = true, -- Personalized Goblin S.C.R.A.P.per
        [2289] = true, -- Venture Co-ordinator
        [2290] = true, -- Asset Advocator
        [2291] = true, -- Salvaged Goblin Gazillionaire's Flying Machine
        [2292] = true, -- Margin Manipulator
        [2293] = true, -- Darkfuse Spy-Eye
        [2294] = true, -- Mean Green Flying Machine
        [2295] = true, -- Bilgewater Bombardier
        [2296] = true, -- Delver's Gob-Trotter
        [2298] = true, -- Prized Gladiator's Fel Bat
        [2299] = true, -- Vicious Electro Eel
        [2300] = true, -- Vicious Electro Eel
        [2303] = true, -- Violet Goblin Shredder
        [2304] = true, -- Chaos-Forged Gryphon
        [2305] = true, -- Chaos-Forged Hippogryph
        [2307] = true, -- Chaos-Forged Dreadwing
        [2308] = true, -- Chaos-Forged Wind Rider
        [2313] = true, -- Junkmaestro's Magnetomech
        [2315] = true, -- Timbered Sky Snake
        [2317] = true, -- Enchanted Spellweave Carpet
        [2321] = true, -- Timely Buzzbee
        [2322] = true, -- Thrayir, Eyes of the Siren
        [2324] = true, -- Hooktalon
        [2326] = true, -- Astral Gladiator's Fel Bat
        [2327] = true, -- Lunar Launcher
        [2328] = true, -- Love Witch's Sweeper
        [2329] = true, -- Silvermoon Sweeper
        [2330] = true, -- Twilight Witch's Sweeper
        [2331] = true, -- Sky Witch's Sweeper
        [2332] = true, -- The Breaker's Song
        [2333] = true, -- Soweezi's Vintage Waveshredder
        [2334] = true, -- Bronze Goblin Waveshredder
        [2339] = true, -- Jani's Trashpile
        [2342] = true, -- Meeksi Rufflefur
        [2343] = true, -- Meeksi Softpaw
        [2344] = true, -- Meeksi Rollingpaw
        [2345] = true, -- Meeksi Teatuft
        [2346] = true, -- Meeksi Brewthief
        [2347] = true, -- Savage Alabaster Battle Turtle
        [2469] = true, -- Prismatic Snapdragon
        [2470] = true, -- Nightfall Skyreaver
        [2471] = true, -- Ur'zul Fleshripper
        [2473] = true, -- Broodling of Sinestra
        [2474] = true, -- Copper-Maned Quilen
        [2478] = true, -- Blazing Royal Fire Hawk
        [2480] = true, -- Crimson Shreddertank
        [2482] = true, -- Lively Darkmoon Charger
        [2483] = true, -- Violet Darkmoon Charger
        [2487] = true, -- The Big G
        [2488] = true, -- Shimmermist Free Runner
        [2489] = true, -- Pearlescent Butterfly
        [2491] = true, -- Ruby Butterfly
        [2495] = true, -- Emerald Snail
        [2496] = true, -- Void-Scarred Gryphon
        [2497] = true, -- Void-Forged Stallion
        [2498] = true, -- Void-Scarred Pack Mother
        [2499] = true, -- Void-Scarred Windrider
        [2500] = true, -- Ny'alothan Shadow Worm
        [2501] = true, -- Corruption of the Aspects
        [2502] = true, -- Void-Crystal Panther
        [2504] = true, -- Spotted Black Riding Goat
        [2505] = true, -- Resplendent K'arroc
        [2507] = true, -- Prototype A.S.M.R.
        [2508] = true, -- Enterprising Shreddertank
        [2510] = true, -- Terror of the Wastes
        [2511] = true, -- Terror of the Night
        [2512] = true, -- Delver's Mana-Skimmer
        [2518] = true, -- Chrono Corsair
        [2519] = true, -- Radiant Imperial Lynx
        [2520] = true, -- Spring Harvesthog
        [2524] = true, -- Coldflame Cormaera
        [2525] = true, -- Prophet's Great Raven
        [2526] = true, -- Felborn Cormaera
        [2527] = true, -- Molten Cormaera
        [2529] = true, -- Archmage's Great Raven
        [2531] = true, -- Tyrannotort
        [2532] = true, -- Herald of Sa'bak
        [2535] = true, -- Void-Scarred Lynx
        [2542] = true, -- Bloodhunter Fel Bat
        [2544] = true, -- Ashplague Fel Bat
        [2546] = true, -- Wretched Fel Bat
        [2549] = true, -- Umbral K'arroc
        [2550] = true, -- K'arroc Swiftwing
        [2552] = true, -- Lavender K'arroc
        [2555] = true, -- The Bone Freezer
        [2556] = true, -- Ruby Void Creeper
        [2557] = true, -- Acidic Void Creeper
        [2560] = true, -- Blue Barry
        [2561] = true, -- Curious Slateback
        [2566] = true, -- Lana'thel's Crimson Cascade
        [2567] = true, -- Voidwing Dragonhawk
        [2568] = true, -- Lightwing Dragonhawk
        [2569] = true, -- Unbound Star-Eater
        [2570] = true, -- Vicious Void Creeper
        [2571] = true, -- Vicious Void Creeper
        [2572] = true, -- Banshee's Chilling Charger
        [2573] = true, -- Grandiose Grrloc
        [2574] = true, -- Snowy Highmountain Eagle
        [2575] = true, -- Grandmaster's Prophetic Board
        [2577] = true, -- Grandmaster's Royal Board
        [2579] = true, -- Forsaken's Grotesque Charger
        [2580] = true, -- Wailing Banshee's Charger
        [2586] = true, -- Moonlit Nightsaber
        [2587] = true, -- Ivory Savagemane
        [2593] = true, -- Slag Basilisk
        [2598] = true, -- Voidlight Surger
        [2600] = true, -- Unarmored Deathtusk Felboar
        [2601] = true, -- Pearlescent Krolusk
        [2602] = true, -- Translocated Gorger
        [2603] = true, -- Sthaarbs's Last Lunch
        [2604] = true, -- OC91 Chariot
        [2605] = true, -- Inarius' Charger
        [2606] = true, -- Royal Voidwing
        [2608] = true, -- Lightforged Mechsuit
        [2612] = true, -- Void-Forged Overseer
        [2618] = true, -- Thunder-Ridged Elekk
        [2619] = true, -- Cinder-Seared Elekk
        [2620] = true, -- Void-Razed Elekk
        [2621] = true, -- Legion-Forged Elekk
        [2623] = true, -- The Headless Horseman's Ghoulish Charger
        [2625] = true, -- The Headless Horseman's Hallowed Charger
        [2627] = true, -- High Shaman's Aerie Gryphon
        [2628] = true, -- Cinder-Plumed Highland Gryphon
        [2630] = true, -- Ornery Breezestrider
        [2631] = true, -- Scarlet Void Flyer
        [2632] = true, -- Astral Aurochs
        [2633] = true, -- Azure Void Flyer
        [2634] = true, -- Scorching Valor
        [2640] = true, -- Brewfest Bomber
        [2645] = true, -- Kalu'ak Crest-Horn
        [2653] = true, -- Ghastly Ur'zul
        [2655] = true, -- Phase-Lost Slateback
        [2660] = true, -- Leystone Basilisk
        [2661] = true, -- Felslate Basilisk
        [2662] = true, -- Aquamarine Basilisk
        [2663] = true, -- Illidari Dreadstalker
        [2664] = true, -- Illidari Blightstalker
        [2665] = true, -- Highland Elderhorn
        [2666] = true, -- Treetop Highmountain Eagle
        [2670] = true, -- Arcberry Manasaber
        [2671] = true, -- Fel-Scarred Mana Ray
        [2672] = true, -- Bloodtooth Mana Ray
        [2673] = true, -- Albino Mana Ray
        [2674] = true, -- Luminous Mana Ray
        [2675] = true, -- Twilight Courser
        [2676] = true, -- Golden Sunrunner
        [2677] = true, -- Turquoise Courser
        [2678] = true, -- Gloomdark Nightmare
        [2679] = true, -- Bonesteed of Triumph
        [2681] = true, -- Bonesteed of Bloodshed
        [2682] = true, -- Bonesteed of Plague
        [2683] = true, -- Bonesteed of Oblivion
        [2686] = true, -- Longhorned Sable Talbuk
        [2688] = true, -- Garnet Ruinstrider
        [2689] = true, -- Longhorned Bleakhoof Talbuk
        [2690] = true, -- Longhorned Argussian Talbuk
        [2691] = true, -- Longhorned Beryl Talbuk
        [2696] = true, -- Highlands Gobbler
        [2699] = true, -- Prized Turkey
        [2705] = true, -- Chestnut Courser
        [2706] = true, -- Brimstone Courser
        [2719] = true, -- Starspark Netherdrake
        [2720] = true, -- Felscorned Vilebrood Vanquisher
        [2721] = true, -- Slayer's Felscorned Shrieker
        [2723] = true, -- Felscorned Wolfhawk
        [2724] = true, -- Archmage's Felscorned Disc
        [2725] = true, -- Felscorned Grandmaster's Companion
        [2726] = true, -- Felscorned Highlord's Charger
        [2727] = true, -- High Priest's Felscorned Seeker
        [2728] = true, -- Shadowblade's Felscorned Omen
        [2729] = true, -- Farseer's Felscorned Tempest
        [2730] = true, -- Felscorned Netherlord's Dreadsteed
        [2731] = true, -- Felscorned War Wyrm
        [2732] = true, -- Cobalt Phase-Hunter
        [2742] = true, -- Thunderhoof Celestial
        [2743] = true, -- Stormgilded Celestial
        [2795] = true, -- Bronze Wilderling
        [2796] = true, -- Bronze Aquilon
        [2797] = true, -- Bronze Corpsefly
        [2798] = true, -- Bronze Gravewing
        [2802] = true, -- Geargrinder Mk. 11
        [2804] = true, -- Crimson Lupine
        [2807] = true, -- Brawlin' Bruno
        [2808] = true, -- Ballistic Bronco
        [2815] = true, -- Snowpaw Glimmerfur Prowler
        [2823] = true, -- Savage Crimson Battle Turtle
    },

    [11] = { -- Midnight
        [2186] = true, -- Blue Old God Fish Mount
        [2187] = true, -- Underlight Shorestalker
        [2200] = true, -- [PH] Nightsaber Horde Mount White
        [2202] = true, -- [PH] Alliance Wolf Mount
        [2241] = true, -- Plunderlord's Weathered Crocolisk
        [2262] = true, -- Harmonious Salutations Bear
        [2481] = true, -- Midnight Darkmoon Charger
        [2484] = true, -- Snowy Darkmoon Charger
        [2492] = true, -- Spring Butterfly
        [2494] = true, -- Midnight Butterfly
        [2521] = true, -- Summer Harvesthog
        [2522] = true, -- Winter Harvesthog
        [2523] = true, -- Autumn Harvesthog
        [2528] = true, -- Lavaborn Cormaera
        [2576] = true, -- Grandmaster's Deep Board
        [2578] = true, -- Grandmaster's Smokey Board
        [2581] = true, -- Banshee's Sickening Charger
        [2622] = true, -- The Headless Horseman's Chilling Charger
        [2624] = true, -- The Headless Horseman's Burning Charger
        [2626] = true, -- Adorned Northeron Gryphon
        [2629] = true, -- Emberwing Sky Guide
        [2649] = true, -- Sharktested Crest-Horn
        [2650] = true, -- Floestrider Crest-Horn
        [2651] = true, -- Cragstepper Crest-Horn
        [2697] = true, -- Quirky Turkey
        [2698] = true, -- Murky Turkey
        [2803] = true, -- Skypaw Glimmerfur
        [2825] = true, -- Cloudborn Razorwing
    },

}

local MountIDtoExpansion = {}
for expansionID, mounts in pairs(Expansion) do
    for mountID in pairs(mounts) do
        MountIDtoExpansion[mountID] = expansionID
    end
end

function LM.MountDB.GetExpansionByID(id)
    return MountIDtoExpansion[id] or 11
end
